/**
 * Database types for the Community Growth Platform.
 *
 * THIS FILE IS A PLACEHOLDER.
 * The authoritative version is generated by the Supabase CLI:
 *   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.types.ts
 *
 * After you create your Supabase project and run migrations,
 * regenerate this file using the command above.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          discord_id: string | null
          discord_username: string | null
          referral_code: string
          referred_by_id: string | null
          role: Database['public']['Enums']['user_role']
          status: Database['public']['Enums']['user_status']
          onboarding_steps: string[]
          notify_email: boolean
          notify_discord: boolean
          upi_id: string | null
          created_at: string
          updated_at: string
          last_login_at: string | null
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          discord_id?: string | null
          discord_username?: string | null
          referral_code: string
          referred_by_id?: string | null
          role?: Database['public']['Enums']['user_role']
          status?: Database['public']['Enums']['user_status']
          onboarding_steps?: string[]
          notify_email?: boolean
          notify_discord?: boolean
          upi_id?: string | null
          created_at?: string
          updated_at?: string
          last_login_at?: string | null
        }
        Update: {
          full_name?: string | null
          discord_id?: string | null
          discord_username?: string | null
          onboarding_steps?: string[]
          notify_email?: boolean
          notify_discord?: boolean
          upi_id?: string | null
          updated_at?: string
          last_login_at?: string | null
          // Admin-only updates
          role?: Database['public']['Enums']['user_role']
          status?: Database['public']['Enums']['user_status']
        }
        Relationships: [
          {
            foreignKeyName: 'profiles_id_fkey'
            columns: ['id']
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'profiles_referred_by_id_fkey'
            columns: ['referred_by_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      reddit_accounts: {
        Row: {
          id: string
          profile_id: string
          username: string
          karma: number | null
          account_age_days: number | null
          cqs_score: number | null
          verification_status: Database['public']['Enums']['reddit_verification']
          admin_notes: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          username: string
          karma?: number | null
          account_age_days?: number | null
          cqs_score?: number | null
          verification_status?: Database['public']['Enums']['reddit_verification']
          admin_notes?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          username?: string
          karma?: number | null
          account_age_days?: number | null
          cqs_score?: number | null
          verification_status?: Database['public']['Enums']['reddit_verification']
          admin_notes?: string | null
          is_active?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'reddit_accounts_profile_id_fkey'
            columns: ['profile_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      clients: {
        Row: {
          id: string
          name: string
          slug: string
          description: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          slug?: string
          description?: string | null
          is_active?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      client_users: {
        Row: {
          id: string
          profile_id: string
          client_id: string
          permissions: string[]
          created_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          client_id: string
          permissions?: string[]
          created_at?: string
        }
        Update: {
          permissions?: string[]
        }
        Relationships: [
          {
            foreignKeyName: 'client_users_profile_id_fkey'
            columns: ['profile_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'client_users_client_id_fkey'
            columns: ['client_id']
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
        ]
      }
      projects: {
        Row: {
          id: string
          client_id: string
          name: string
          description: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id: string
          name: string
          description?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          description?: string | null
          is_active?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'projects_client_id_fkey'
            columns: ['client_id']
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
        ]
      }
      task_templates: {
        Row: {
          id: string
          name: string
          task_type: Database['public']['Enums']['task_type']
          instructions: string
          subreddit: string | null
          post_title: string | null
          post_body: string | null
          thread_url: string | null
          default_reward_inr: number | null
          default_deadline_h: number
          is_active: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          task_type: Database['public']['Enums']['task_type']
          instructions: string
          subreddit?: string | null
          post_title?: string | null
          post_body?: string | null
          thread_url?: string | null
          default_reward_inr?: number | null
          default_deadline_h?: number
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          instructions?: string
          subreddit?: string | null
          post_title?: string | null
          post_body?: string | null
          thread_url?: string | null
          default_reward_inr?: number | null
          default_deadline_h?: number
          is_active?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      contributor_rates: {
        Row: {
          id: string
          profile_id: string | null
          task_type: Database['public']['Enums']['task_type']
          rate_inr: number
          effective_from: string
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          profile_id?: string | null
          task_type: Database['public']['Enums']['task_type']
          rate_inr: number
          effective_from?: string
          created_by?: string | null
          created_at?: string
        }
        Update: {
          rate_inr?: number
          effective_from?: string
        }
        Relationships: []
      }
      tasks: {
        Row: {
          id: string
          project_id: string
          template_id: string | null
          task_type: Database['public']['Enums']['task_type']
          title: string
          instructions: string
          subreddit: string | null
          thread_url: string | null
          post_title: string | null
          post_body: string | null
          base_reward_inr: number
          deadline_hours: number
          max_assignments: number
          status: Database['public']['Enums']['task_status']
          internal_notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
          search_vector: string | null
        }
        Insert: {
          id?: string
          project_id: string
          template_id?: string | null
          task_type: Database['public']['Enums']['task_type']
          title: string
          instructions: string
          subreddit?: string | null
          thread_url?: string | null
          post_title?: string | null
          post_body?: string | null
          base_reward_inr: number
          deadline_hours?: number
          max_assignments?: number
          status?: Database['public']['Enums']['task_status']
          internal_notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          title?: string
          instructions?: string
          subreddit?: string | null
          thread_url?: string | null
          post_title?: string | null
          post_body?: string | null
          base_reward_inr?: number
          deadline_hours?: number
          max_assignments?: number
          status?: Database['public']['Enums']['task_status']
          internal_notes?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'tasks_project_id_fkey'
            columns: ['project_id']
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      assignments: {
        Row: {
          id: string
          task_id: string
          profile_id: string
          reddit_account_id: string
          rate_snapshot_inr: number
          status: Database['public']['Enums']['assignment_status']
          assigned_at: string
          deadline_at: string
          started_at: string | null
          completed_at: string | null
          admin_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          task_id: string
          profile_id: string
          reddit_account_id: string
          rate_snapshot_inr?: number
          status?: Database['public']['Enums']['assignment_status']
          assigned_at?: string
          deadline_at?: string
          started_at?: string | null
          completed_at?: string | null
          admin_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          status?: Database['public']['Enums']['assignment_status']
          started_at?: string | null
          completed_at?: string | null
          admin_notes?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'assignments_task_id_fkey'
            columns: ['task_id']
            referencedRelation: 'tasks'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'assignments_profile_id_fkey'
            columns: ['profile_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'assignments_reddit_account_id_fkey'
            columns: ['reddit_account_id']
            referencedRelation: 'reddit_accounts'
            referencedColumns: ['id']
          },
        ]
      }
      submissions: {
        Row: {
          id: string
          assignment_id: string
          profile_id: string
          reddit_url: string
          detected_type: string | null
          screenshot_refs: Json
          insight_text: string | null
          contributor_notes: string | null
          attempt_number: number
          status: Database['public']['Enums']['submission_status']
          submitted_at: string
          reviewed_by: string | null
          reviewed_at: string | null
          review_notes: string | null
          sheets_logged: boolean
          discord_sent: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          assignment_id: string
          profile_id: string
          reddit_url: string
          detected_type?: string | null
          screenshot_refs?: Json
          insight_text?: string | null
          contributor_notes?: string | null
          attempt_number?: number
          status?: Database['public']['Enums']['submission_status']
          submitted_at?: string
          reviewed_by?: string | null
          reviewed_at?: string | null
          review_notes?: string | null
          sheets_logged?: boolean
          discord_sent?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          reddit_url?: string
          detected_type?: string | null
          screenshot_refs?: Json
          insight_text?: string | null
          contributor_notes?: string | null
          status?: Database['public']['Enums']['submission_status']
          reviewed_by?: string | null
          reviewed_at?: string | null
          review_notes?: string | null
          sheets_logged?: boolean
          discord_sent?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'submissions_assignment_id_fkey'
            columns: ['assignment_id']
            referencedRelation: 'assignments'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'submissions_profile_id_fkey'
            columns: ['profile_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      insights: {
        Row: {
          id: string
          profile_id: string
          submission_id: string | null
          text_content: string | null
          image_refs: Json
          drive_folder_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          submission_id?: string | null
          text_content?: string | null
          image_refs?: Json
          drive_folder_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          text_content?: string | null
          image_refs?: Json
          updated_at?: string
        }
        Relationships: []
      }
      payments: {
        Row: {
          id: string
          profile_id: string
          assignment_id: string | null
          amount_inr: number
          payment_type: Database['public']['Enums']['payment_type']
          status: Database['public']['Enums']['payment_status']
          approved_at: string | null
          approved_by: string | null
          paid_at: string | null
          paid_by: string | null
          payment_method: string | null
          transaction_ref: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          assignment_id?: string | null
          amount_inr: number
          payment_type?: Database['public']['Enums']['payment_type']
          status?: Database['public']['Enums']['payment_status']
          approved_at?: string | null
          approved_by?: string | null
          paid_at?: string | null
          paid_by?: string | null
          payment_method?: string | null
          transaction_ref?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          status?: Database['public']['Enums']['payment_status']
          approved_at?: string | null
          approved_by?: string | null
          paid_at?: string | null
          paid_by?: string | null
          payment_method?: string | null
          transaction_ref?: string | null
          notes?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      referrals: {
        Row: {
          id: string
          referrer_id: string
          referred_id: string
          bonus_amount_inr: number
          bonus_status: Database['public']['Enums']['referral_status']
          unlocking_assignment_id: string | null
          awarded_at: string | null
          payment_id: string | null
          revoked_at: string | null
          revoked_by: string | null
          revoke_reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          referrer_id: string
          referred_id: string
          bonus_amount_inr?: number
          bonus_status?: Database['public']['Enums']['referral_status']
          unlocking_assignment_id?: string | null
          awarded_at?: string | null
          payment_id?: string | null
          revoked_at?: string | null
          revoked_by?: string | null
          revoke_reason?: string | null
          created_at?: string
        }
        Update: {
          bonus_status?: Database['public']['Enums']['referral_status']
          unlocking_assignment_id?: string | null
          awarded_at?: string | null
          payment_id?: string | null
          revoked_at?: string | null
          revoked_by?: string | null
          revoke_reason?: string | null
        }
        Relationships: []
      }
      notifications: {
        Row: {
          id: string
          profile_id: string
          type: string
          title: string
          body: string | null
          action_url: string | null
          metadata: Json
          is_read: boolean
          discord_sent: boolean
          discord_sent_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          type: string
          title: string
          body?: string | null
          action_url?: string | null
          metadata?: Json
          is_read?: boolean
          discord_sent?: boolean
          discord_sent_at?: string | null
          created_at?: string
        }
        Update: {
          is_read?: boolean
          discord_sent?: boolean
          discord_sent_at?: string | null
        }
        Relationships: []
      }
      client_revenue: {
        Row: {
          id: string
          client_id: string
          project_id: string | null
          period_month: string
          revenue_inr: number
          notes: string | null
          entered_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id: string
          project_id?: string | null
          period_month: string
          revenue_inr: number
          notes?: string | null
          entered_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          revenue_inr?: number
          notes?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      drive_folder_cache: {
        Row: {
          id: string
          path_key: string
          drive_folder_id: string
          created_at: string
        }
        Insert: {
          id?: string
          path_key: string
          drive_folder_id: string
          created_at?: string
        }
        Update: {
          drive_folder_id?: string
        }
        Relationships: []
      }
      audit_logs: {
        Row: {
          id: string
          actor_id: string | null
          actor_role: string | null
          action: string
          target_type: string | null
          target_id: string | null
          before_state: Json | null
          after_state: Json | null
          ip_address: string | null
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          actor_id?: string | null
          actor_role?: string | null
          action: string
          target_type?: string | null
          target_id?: string | null
          before_state?: Json | null
          after_state?: Json | null
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
        Update: never  // Audit logs are append-only
        Relationships: []
      }
      business_inquiries: {
        Row: {
          id: string
          company_name: string
          contact_name: string
          email: string
          website: string | null
          project_description: string
          status: Database['public']['Enums']['inquiry_status']
          created_at: string
        }
        Insert: {
          id?: string
          company_name: string
          contact_name: string
          email: string
          website?: string | null
          project_description: string
          status?: Database['public']['Enums']['inquiry_status']
          created_at?: string
        }
        Update: {
          company_name?: string
          contact_name?: string
          email?: string
          website?: string | null
          project_description?: string
          status?: Database['public']['Enums']['inquiry_status']
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      get_my_role: {
        Args: Record<string, never>
        Returns: string
      }
      promote_to_admin: {
        Args: { p_email: string }
        Returns: void
      }
    }
    Enums: {
      user_role: 'contributor' | 'admin' | 'client'
      user_status: 'pending' | 'approved' | 'rejected' | 'suspended'
      reddit_verification: 'unverified' | 'pending' | 'verified' | 'rejected'
      task_type: 'comment' | 'post' | 'moderation'
      task_status: 'draft' | 'open' | 'fully_assigned' | 'completed' | 'cancelled'
      assignment_status:
        | 'assigned'
        | 'in_progress'
        | 'submitted'
        | 'under_review'
        | 'approved'
        | 'rejected'
        | 'paid'
      submission_status: 'pending' | 'under_review' | 'approved' | 'rejected'
      payment_type: 'task' | 'referral_bonus'
      payment_status: 'pending' | 'approved' | 'paid'
      referral_status: 'pending' | 'awarded' | 'revoked'
      inquiry_status: 'new' | 'contacted' | 'qualified' | 'closed'
    }
    CompositeTypes: Record<string, never>
  }
}

// Convenience type aliases
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T]

export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
